apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-backend
  template:
    metadata:
      labels:
        app: my-app-backend
    spec:
      containers:
        - name: my-app-backend
          image: my-backend-image:v1  # Remplacer par ton image
          ports:
            - containerPort: 8080
