replicaCount: 2

image:
  repository: backend-app
  tag: latest
  pullPolicy: IfNotPresent

postgres:
  image:
    repository: postgres
    tag: 15
  username: admin
  password: password
  database: mydb

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: backend.local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
