apiVersion: v1
kind: Service
metadata:
  name: my-postgresql
  namespace: my-application
spec:
  ports:
    - port: 5432
  selector:
    app: postgresql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: my-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:13
        env:
          - name: POSTGRES_DB
            value: mydb
          - name: SPRING_POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: SPRING_POSTGRES_USERNAME
          - name: SPRING_POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: SPRING_POSTGRES_PASSWORD
        ports:
          - containerPort: 5432