apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  namespace: my-application
spec:
  replicas: {{ .Values.replicaCountBack }}
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: back
        image: {{ .Values.image.back.repository }}:{{ .Values.image.back.tag }}
        imagePullPolicy: {{ .Values.image.back.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_POSTGRES_URL
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: SPRING_POSTGRES_URL
          - name: SPRING_POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: SPRING_POSTGRES_USERNAME
          - name: SPRING_POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: SPRING_POSTGRES_PASSWORD
      hostAliases:
        - ip: "217.182.211.190"
          hostnames:
            - "my-db-test.io"