apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  namespace: my-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: back
        image: {{ .Values.image.back.repository }}:{{ .Values.image.back.tag }}
        imagePullPolicy: {{ .Values.image.back.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: SPRING_POSTGRES_USERNAME
        - name: SPRING_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: SPRING_POSTGRES_PASSWORD
        - name: SPRING_POSTGRES_URL
          value: "jdbc:postgresql://my-postgresql.my-application.svc.cluster.local:5432/mydb"
