name: Deploy to Kubernetes with Helm

on:
  workflow_dispatch:  # Permet un déclenchement manuel via l'interface GitHub

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0
      id: install

    - name: Set up Kubernetes context
      run: |
        kubectl config set-cluster my-cluster --server=https://192.168.49.2:8443 --insecure-skip-tls-verify=true
        kubectl config set-credentials my-user --token=${{ secrets.TOKEN_KUBE }}
        kubectl config set-context my-cluster-context --cluster=my-cluster --user=my-user --namespace=my-application
        kubectl config use-context my-cluster-context

    - name: Deploy to Kubernetes with Helm
      run: |
        helm upgrade --install my-application ./my-application-chart \
          --namespace my-application \
          --set image.front.repository=mehdiskh/my-application-front \
          --set image.front.tag=1.0 \
          --set image.back.repository=mehdiskh/my-application-back \
          --set image.back.tag=1.0 \
          --set postgres.username=${{ secrets.POSTGRES_USERNAME }} \
          --set postgres.password=${{ secrets.POSTGRES_PASSWORD }} \
          --set postgres.url=${{ secrets.POSTGRES_URL }} \
          --set ingress.hostname=${{ secrets.INGRESS_HOSTNAME }}

