name: Deploy to Kubernetes with Helm

on:
  workflow_dispatch:  # Permet un déclenchement manuel via l'interface GitHub

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.16.4

    - name: Set up Kubernetes context
      run: |
        kubectl config set-cluster ${{ secrets.KUBE_CLUSTER_NAME }} --server=${{ secrets.KUBE_SERVER }} --certificate-authority=${{ secrets.KUBE_CA_CERT }}
        kubectl config set-credentials ${{ secrets.KUBE_USER }} --token=${{ secrets.KUBE_TOKEN }}
        kubectl config set-context ${{ secrets.KUBE_CONTEXT }} --cluster=${{ secrets.KUBE_CLUSTER_NAME }} --user=${{ secrets.KUBE_USER }} --namespace=my-application
        kubectl config use-context ${{ secrets.KUBE_CONTEXT }}

    - name: Deploy to Kubernetes with Helm
      run: |
        helm upgrade --install my-application ./my-application-chart \
          --namespace my-application \
          --set image.front.repository=${{ secrets.FRONT_IMAGE_REPO }} \
          --set image.front.tag=${{ secrets.FRONT_IMAGE_TAG }} \
          --set image.back.repository=${{ secrets.BACK_IMAGE_REPO }} \
          --set image.back.tag=${{ secrets.BACK_IMAGE_TAG }} \
          --set postgres.username=${{ secrets.POSTGRES_USERNAME }} \
          --set postgres.password=${{ secrets.POSTGRES_PASSWORD }} \
          --set postgres.url=${{ secrets.POSTGRES_URL }} \
          --set ingress.hostname=${{ secrets.INGRESS_HOSTNAME }}

