name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build and push backend
      run: |
        docker build -t mehdiskh/my-application/backend:1.0 ./backend/
        docker push mehdiskh/my-application/backend:1.0

  build-frontend:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build and push frontend
      run: |
        docker build -t mehdiskh/my-application/frontend:1.0 ./frontend/
        docker push mehdiskh/my-application/frontend:1.0
